#!/usr/bin/env bash
set -euo pipefail

# AgentCrew installer
# Usage: curl -fsSL https://agentcrew.helmcode.com/install.sh | bash

REPO_BASE="https://raw.githubusercontent.com/helmcode/agent_crew_landing/main"
INSTALL_DIR="$HOME/.agentcrew"

# ── Colors ──────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

banner() {
  echo ""
  echo -e "${BLUE}${BOLD}"
  echo "    _                    _    ____                   "
  echo "   / \   __ _  ___ _ __ | |_ / ___|_ __ _____      __"
  echo "  / _ \ / _\` |/ _ \ '_ \| __| |   | '__/ _ \ \ /\ / /"
  echo " / ___ \ (_| |  __/ | | | |_| |___| | |  __/\ V  V / "
  echo "/_/   \_\__, |\___|_| |_|\__|\____|_|  \___| \_/\_/  "
  echo "        |___/                                        "
  echo -e "${NC}"
  echo -e "${CYAN}  Multi-Agent AI Team Orchestrator${NC}"
  echo ""
}

info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
fail()    { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── Preflight checks ───────────────────────────────────────────────
check_dependencies() {
  info "Checking dependencies..."

  if ! command -v docker &>/dev/null; then
    fail "Docker is not installed. Install it from https://docs.docker.com/get-docker/"
  fi
  success "Docker found: $(docker --version | head -1)"

  if ! docker compose version &>/dev/null; then
    fail "Docker Compose v2 is not installed. Install it from https://docs.docker.com/compose/install/"
  fi
  success "Docker Compose found: $(docker compose version --short)"

  if ! docker info &>/dev/null 2>&1; then
    fail "Docker daemon is not running. Please start Docker and try again."
  fi
  success "Docker daemon is running"

  if ! command -v curl &>/dev/null; then
    fail "curl is not installed. Please install curl and try again."
  fi
}

# ── Install ─────────────────────────────────────────────────────────
install() {
  # Generate NATS auth token
  NATS_TOKEN=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

  # Create install directory
  if [[ -d "$INSTALL_DIR" ]]; then
    warn "Directory '$INSTALL_DIR' already exists."
    read -rp "Overwrite configuration? [y/N]: " overwrite </dev/tty
    if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
      fail "Installation cancelled."
    fi
  fi

  mkdir -p "$INSTALL_DIR"

  info "Downloading docker-compose.yml..."
  curl -fsSL -o "$INSTALL_DIR/docker-compose.yml" "$REPO_BASE/docker-compose.yml"
  success "docker-compose.yml downloaded"

  # Create .env file
  info "Generating configuration..."
  {
    echo "# AgentCrew configuration — generated by install.sh"
    echo "NATS_AUTH_TOKEN=$NATS_TOKEN"
    echo "# API_PORT=3000"
    echo "# FRONTEND_PORT=8080"
  } > "$INSTALL_DIR/.env"
  success ".env created with secure NATS token"

  # Start the stack
  echo ""
  info "Pulling images and starting AgentCrew..."
  docker compose -f "$INSTALL_DIR/docker-compose.yml" --env-file "$INSTALL_DIR/.env" up -d

  # Wait for API to be ready
  info "Waiting for services to be ready..."
  local retries=0
  local max_retries=30
  while ! curl -sf "http://localhost:3000/api/health" &>/dev/null; do
    retries=$((retries + 1))
    if [[ $retries -ge $max_retries ]]; then
      warn "API server did not respond after 30s. It may still be starting up."
      break
    fi
    sleep 1
  done

  if [[ $retries -lt $max_retries ]]; then
    success "All services are running"
  fi
}

# ── Summary ─────────────────────────────────────────────────────────
summary() {
  echo ""
  echo -e "${GREEN}${BOLD}── AgentCrew is running! ──${NC}"
  echo ""
  echo -e "  ${BOLD}Open:${NC}  http://localhost:8080"
  echo ""
  echo -e "  ${YELLOW}Next step: go to Settings (gear icon) and add your"
  echo -e "  Anthropic API key or OAuth token to start deploying agents.${NC}"
  echo ""
  echo -e "  ${BOLD}Manage:${NC}"
  echo "    cd $INSTALL_DIR"
  echo "    docker compose logs -f        # View logs"
  echo "    docker compose down            # Stop"
  echo "    docker compose up -d           # Start"
  echo ""
  echo -e "  ${BOLD}Docs:${NC} https://agentcrew.helmcode.com/docs"
  echo ""
}

# ── Main ────────────────────────────────────────────────────────────
main() {
  banner
  check_dependencies
  install
  summary
}

main
