#!/usr/bin/env bash
set -euo pipefail

# AgentCrew installer
# Usage: curl -fsSL https://agentcrew.helmcode.com/install.sh | bash

REPO_BASE="https://raw.githubusercontent.com/helmcode/agent_crew_landing/main"
INSTALL_DIR="agentcrew"

# ── Colors ──────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

banner() {
  echo ""
  echo -e "${BLUE}${BOLD}"
  echo "    _                    _    ____                   "
  echo "   / \   __ _  ___ _ __ | |_ / ___|_ __ _____      __"
  echo "  / _ \ / _\` |/ _ \ '_ \| __| |   | '__/ _ \ \ /\ / /"
  echo " / ___ \ (_| |  __/ | | | |_| |___| | |  __/\ V  V / "
  echo "/_/   \_\__, |\___|_| |_|\__|\____|_|  \___| \_/\_/  "
  echo "        |___/                                        "
  echo -e "${NC}"
  echo -e "${CYAN}  Multi-Agent AI Team Orchestrator${NC}"
  echo ""
}

info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}   $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
fail()    { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ── Preflight checks ───────────────────────────────────────────────
check_dependencies() {
  info "Checking dependencies..."

  if ! command -v docker &>/dev/null; then
    fail "Docker is not installed. Install it from https://docs.docker.com/get-docker/"
  fi
  success "Docker found: $(docker --version | head -1)"

  if ! docker compose version &>/dev/null; then
    fail "Docker Compose v2 is not installed. Install it from https://docs.docker.com/compose/install/"
  fi
  success "Docker Compose found: $(docker compose version --short)"

  if ! docker info &>/dev/null 2>&1; then
    fail "Docker daemon is not running. Please start Docker and try again."
  fi
  success "Docker daemon is running"

  if ! command -v curl &>/dev/null; then
    fail "curl is not installed. Please install curl and try again."
  fi
}

# ── Gather user input ──────────────────────────────────────────────
gather_config() {
  echo ""
  echo -e "${BOLD}── Configuration ──${NC}"
  echo ""
  echo "AgentCrew needs an Anthropic API key or a Claude Code OAuth token."
  echo "You can add or change this later from the Settings page in the UI."
  echo ""

  AUTH_TYPE=""
  AUTH_VALUE=""

  echo -e "  ${BOLD}1)${NC} Anthropic API key  (from console.anthropic.com)"
  echo -e "  ${BOLD}2)${NC} Claude Code OAuth token"
  echo -e "  ${BOLD}3)${NC} Skip — I'll configure it later in the UI"
  echo ""

  while true; do
    read -rp "Choose an option [1/2/3]: " choice
    case "$choice" in
      1)
        echo ""
        read -rp "Enter your Anthropic API key: " AUTH_VALUE
        if [[ -z "$AUTH_VALUE" ]]; then
          warn "Empty value. Skipping — you can set it later in Settings."
        else
          AUTH_TYPE="ANTHROPIC_API_KEY"
          success "API key saved"
        fi
        break
        ;;
      2)
        echo ""
        read -rp "Enter your Claude Code OAuth token: " AUTH_VALUE
        if [[ -z "$AUTH_VALUE" ]]; then
          warn "Empty value. Skipping — you can set it later in Settings."
        else
          AUTH_TYPE="CLAUDE_CODE_OAUTH_TOKEN"
          success "OAuth token saved"
        fi
        break
        ;;
      3)
        warn "Skipping authentication — remember to set it in Settings before deploying agents."
        break
        ;;
      *)
        echo "  Please enter 1, 2, or 3."
        ;;
    esac
  done

  # Ports
  echo ""
  read -rp "Frontend port [8080]: " FRONTEND_PORT
  FRONTEND_PORT="${FRONTEND_PORT:-8080}"

  read -rp "API port [3000]: " API_PORT
  API_PORT="${API_PORT:-3000}"
}

# ── Install ─────────────────────────────────────────────────────────
install() {
  # Generate NATS auth token
  NATS_TOKEN=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')

  # Create install directory
  if [[ -d "$INSTALL_DIR" ]]; then
    warn "Directory '$INSTALL_DIR' already exists."
    read -rp "Overwrite configuration? [y/N]: " overwrite
    if [[ "${overwrite,,}" != "y" ]]; then
      fail "Installation cancelled."
    fi
  fi

  mkdir -p "$INSTALL_DIR"

  info "Downloading docker-compose.yml..."
  curl -fsSL -o "$INSTALL_DIR/docker-compose.yml" "$REPO_BASE/docker-compose.yml"
  success "docker-compose.yml downloaded"

  # Create .env file
  info "Generating .env configuration..."
  {
    echo "# AgentCrew configuration — generated by install.sh"
    echo "NATS_AUTH_TOKEN=$NATS_TOKEN"
    echo "API_PORT=$API_PORT"
    echo "FRONTEND_PORT=$FRONTEND_PORT"
  } > "$INSTALL_DIR/.env"
  success ".env file created with secure NATS token"

  # Start the stack
  echo ""
  info "Starting AgentCrew..."
  docker compose -f "$INSTALL_DIR/docker-compose.yml" --env-file "$INSTALL_DIR/.env" up -d

  # Wait for API to be ready
  info "Waiting for API server to be ready..."
  local retries=0
  local max_retries=30
  while ! curl -sf "http://localhost:${API_PORT}/api/health" &>/dev/null; do
    retries=$((retries + 1))
    if [[ $retries -ge $max_retries ]]; then
      warn "API server did not respond after 30s. It may still be starting up."
      break
    fi
    sleep 1
  done

  if [[ $retries -lt $max_retries ]]; then
    success "API server is ready"
  fi

  # Set the auth credential via the API if provided
  if [[ -n "$AUTH_TYPE" && -n "$AUTH_VALUE" ]]; then
    info "Configuring $AUTH_TYPE..."
    local response
    response=$(curl -sf -X POST "http://localhost:${API_PORT}/api/settings" \
      -H "Content-Type: application/json" \
      -d "{\"key\":\"$AUTH_TYPE\",\"value\":\"$AUTH_VALUE\"}" 2>&1) || true

    if [[ $? -eq 0 ]]; then
      success "$AUTH_TYPE configured"
    else
      warn "Could not set $AUTH_TYPE automatically. Please set it in Settings."
    fi
  fi
}

# ── Summary ─────────────────────────────────────────────────────────
summary() {
  echo ""
  echo -e "${GREEN}${BOLD}── AgentCrew is running! ──${NC}"
  echo ""
  echo -e "  ${BOLD}UI:${NC}   http://localhost:${FRONTEND_PORT}"
  echo -e "  ${BOLD}API:${NC}  http://localhost:${API_PORT}"
  echo ""
  if [[ -z "$AUTH_TYPE" ]]; then
    echo -e "  ${YELLOW}Remember to set your Anthropic API key or OAuth token"
    echo -e "  in Settings (gear icon) before creating a team.${NC}"
    echo ""
  fi
  echo -e "  ${BOLD}Manage:${NC}"
  echo "    cd $INSTALL_DIR"
  echo "    docker compose logs -f        # View logs"
  echo "    docker compose down            # Stop"
  echo "    docker compose up -d           # Start"
  echo ""
  echo -e "  ${BOLD}Docs:${NC} https://agentcrew.helmcode.com/docs"
  echo ""
}

# ── Main ────────────────────────────────────────────────────────────
main() {
  banner
  check_dependencies
  gather_config
  install
  summary
}

main
